- hosts: servers
  gather_facts: yes 
  become: yes 
  vars_files: 
    - users.yaml
  tasks:
    - name: Add several users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        groups: "wheel"
      loop: "{{ users }}"
